### ISSUE TITLE
Wrong parameter name in userModel when creating user

### ISSUE THREAD

**Issue by FGBxRamel** [MaRcR11/ba-schedule#171]
Hello there! While trying to set this up myself, I encountered an error with the creation of new users.
## Error
When trying log in (first login / register), the following error comes up:
```
Error: user validation failed: lastLogin: Path `lastLogin` is required.
    at ValidationError.inspect (C:\Users\Raziel\Desktop\Dev\Repos\ba-schedule\node_modules\mongoose\lib\error\validation.js:50:26)
    at formatValue (node:internal/util/inspect:804:19)
    at inspect (node:internal/util/inspect:363:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2297:40)
    at formatWithOptions (node:internal/util/inspect:2159:10)
    at console.value (node:internal/console/constructor:351:14)
    at console.warn (node:internal/console/constructor:384:61)
    at userLogin (C:\Users\Raziel\Desktop\Dev\Repos\ba-schedule\server\src\services\schedule.service.js:119:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleRequest (C:\Users\Raziel\Desktop\Dev\Repos\ba-schedule\server\src\controllers\schedule.controller.js:5:20) {
  errors: {
    lastLogin: ValidatorError: Path `lastLogin` is required.
        at validate (C:\Users\Raziel\Desktop\Dev\Repos\ba-schedule\node_modules\mongoose\lib\schematype.js:1365:13)
        at SchemaType.doValidate (C:\Users\Raziel\Desktop\Dev\Repos\ba-schedule\node_modules\mongoose\lib\schematype.js:1349:7)
        at C:\Users\Raziel\Desktop\Dev\Repos\ba-schedule\node_modules\mongoose\lib\document.js:2971:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: [Object],
      kind: 'required',
      path: 'lastLogin',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose:validatorError)]: true
    }
  },
  _message: 'user validation failed'
}
```
## Fix
My suggested fix would be to change line 6 from [createNewUser.helper.js](https://github.com/MaRcR11/ba-schedule/blob/main/server/src/helpers/createNewUser.helper.js) to
```js
lastLogin = Date.now(),
```
The registration works fine with the suggested change.

**Comment by MaRcR11** [comment]
Hi @FGBxRamel,

yeah, you're right.. I recently forgot to change the name of the field from "ts" to "lastLogin"

ty
